### ISSUE TITLE
fails to ignore objects starting with underscore

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-Test-Regexp-Pattern#4]
Regexp::Pattern defines the structure as being a DefHash, and DefHash contains this:

> Properties with names starting with underscore (_) are ignored; this can be used to put extra information.

Running Test::Regexp::Pattern against Regexp::Pattern::License 3.1.95 fails: it contains a semi-internal object _locales which Test::Regexp::Pattern apparently chokes on.

I can remove that object (and I might do that anyway), but seems it should be legal.

**Comment by perlancar** [comment]
Fixed by using Hash::DefHash, released 0.006. Thanks.
