### ISSUE TITLE
should check that each object is a compliant DevHash

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-Test-Regexp-Pattern#5]
According to DESCRIPTION of Regexp::Pattern, "hash values are pattern definitions in the form of defhashes" - which I can only interpret as not only the %RE has itself must be compliant DefHash structure, but each member (i.e. each re object) must also be a compliant DefHash structure.

Currently, Test::Regexp::Pattern uses Hash::DefHash but only to collect re objects.

Please validate DefHash compliance of each re object.

**Comment by perlancar** [comment]
Done in 8884d02, released.

**Comment by jonassmedegaard** [comment]
Thanks!
Seems you haven't pushed the changes to git yet...

**Comment by jonassmedegaard** [comment]
ah no, those missing changes are for an even newer release :-)
